apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  mongodb_user: {{ .Values.backend.secrets.mongodb_user | b64enc }}
  mongodb_pass: {{ .Values.backend.secrets.mongodb_pass | b64enc }}
